name: Build and push

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up docker image
        id: setup
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/ ]]; then
            TAG=$(echo ${GITHUB_REF##*/})
          else
            TAG=$(echo ${GITHUB_SHA::7})
          fi
          IMAGE=${{ secrets.DOCKERHUB_REPOSITORY }}
          echo "tagged_image=${IMAGE}:${TAG}" >> "$GITHUB_OUTPUT"
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
        with:
            driver-opts: |
              env.http_proxy=${{ env.http_proxy }}
              env.https_proxy=${{ env.https_proxy }}
              "env.no_proxy='${{ env.no_proxy }}'"

      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.2.0
        with:
          push: true
          tags: ${{ steps.setup.outputs.tagged_image }}
